development:
  adapter: postgresql
  encoding: unicode
  database: dnb_dev
  username: postgres
  password: postgres
  pool: 5
  host: localhost
  port: 5432


production:
  adapter: postgresql
  encoding: unicode
  database: dnb_prod
  username: postgres
